### ISSUE TITLE
### Morning Session - Peer to peer code review

### ISSUE THREAD

**Issue by enionsouza** [aristides1000/awesome-books-javascript-microverse-project#5]
Great job, @aristides1000 and @Emmanuelaaron!

Your UI looks great and it reminds me a bit of FreeCodeCamp, somehow! 🥇 
> Just as a suggestion, I would recommend the use of `setInterval()` function to update the time output.

Keep it up! 💻

**Comment by Emmanuelaaron** [comment]
Thanks @enionsouza  on it
